# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: poppie/poppie.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'poppie/poppie.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13poppie/poppie.proto\x12\x06poppie\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x01\n\x06Secret\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0e\n\x06secret\x18\x02 \x01(\t\x12$\n\talgorithm\x18\x03 \x01(\x0e\x32\x11.poppie.Algorithm\x12\x0e\n\x06\x64igits\x18\x04 \x01(\r\x12\x0e\n\x06period\x18\x05 \x01(\r\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0clast_used_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"y\n\x12StoreSecretRequest\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0e\n\x06secret\x18\x02 \x01(\t\x12$\n\talgorithm\x18\x03 \x01(\x0e\x32\x11.poppie.Algorithm\x12\x0e\n\x06\x64igits\x18\x04 \x01(\r\x12\x0e\n\x06period\x18\x05 \x01(\r\"?\n\x13StoreSecretResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x19\n\x11verification_code\x18\x02 \x01(\t\"\x1f\n\x0eGetCodeRequest\x12\r\n\x05label\x18\x01 \x01(\t\":\n\x0fGetCodeResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x19\n\x11valid_for_seconds\x18\x02 \x01(\r\"\x14\n\x12ListSecretsRequest\"%\n\x13ListSecretsResponse\x12\x0e\n\x06labels\x18\x01 \x03(\t\"$\n\x13\x44\x65leteSecretRequest\x12\r\n\x05label\x18\x01 \x01(\t\"\'\n\x14\x44\x65leteSecretResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\"0\n\rVaultContents\x12\x1f\n\x07secrets\x18\x01 \x03(\x0b\x32\x0e.poppie.Secret*f\n\tAlgorithm\x12\x19\n\x15\x41LGORITHM_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x41LGORITHM_SHA1\x10\x01\x12\x14\n\x10\x41LGORITHM_SHA256\x10\x02\x12\x14\n\x10\x41LGORITHM_SHA512\x10\x03\x32\xa6\x02\n\rPoppieService\x12\x46\n\x0bStoreSecret\x12\x1a.poppie.StoreSecretRequest\x1a\x1b.poppie.StoreSecretResponse\x12:\n\x07GetCode\x12\x16.poppie.GetCodeRequest\x1a\x17.poppie.GetCodeResponse\x12\x46\n\x0bListSecrets\x12\x1a.poppie.ListSecretsRequest\x1a\x1b.poppie.ListSecretsResponse\x12I\n\x0c\x44\x65leteSecret\x12\x1b.poppie.DeleteSecretRequest\x1a\x1c.poppie.DeleteSecretResponseB.Z,github.com/BarkingIguana/poppie/proto/poppieb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'poppie.poppie_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/BarkingIguana/poppie/proto/poppie'
  _globals['_ALGORITHM']._serialized_start=745
  _globals['_ALGORITHM']._serialized_end=847
  _globals['_SECRET']._serialized_start=65
  _globals['_SECRET']._serialized_end=272
  _globals['_STORESECRETREQUEST']._serialized_start=274
  _globals['_STORESECRETREQUEST']._serialized_end=395
  _globals['_STORESECRETRESPONSE']._serialized_start=397
  _globals['_STORESECRETRESPONSE']._serialized_end=460
  _globals['_GETCODEREQUEST']._serialized_start=462
  _globals['_GETCODEREQUEST']._serialized_end=493
  _globals['_GETCODERESPONSE']._serialized_start=495
  _globals['_GETCODERESPONSE']._serialized_end=553
  _globals['_LISTSECRETSREQUEST']._serialized_start=555
  _globals['_LISTSECRETSREQUEST']._serialized_end=575
  _globals['_LISTSECRETSRESPONSE']._serialized_start=577
  _globals['_LISTSECRETSRESPONSE']._serialized_end=614
  _globals['_DELETESECRETREQUEST']._serialized_start=616
  _globals['_DELETESECRETREQUEST']._serialized_end=652
  _globals['_DELETESECRETRESPONSE']._serialized_start=654
  _globals['_DELETESECRETRESPONSE']._serialized_end=693
  _globals['_VAULTCONTENTS']._serialized_start=695
  _globals['_VAULTCONTENTS']._serialized_end=743
  _globals['_POPPIESERVICE']._serialized_start=850
  _globals['_POPPIESERVICE']._serialized_end=1144
# @@protoc_insertion_point(module_scope)
