# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import poppie_pb2 as poppie_dot_poppie__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in poppie/poppie_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PoppieServiceStub(object):
    """PoppieService provides TOTP secret management and code generation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreSecret = channel.unary_unary(
                '/poppie.PoppieService/StoreSecret',
                request_serializer=poppie_dot_poppie__pb2.StoreSecretRequest.SerializeToString,
                response_deserializer=poppie_dot_poppie__pb2.StoreSecretResponse.FromString,
                _registered_method=True)
        self.GetCode = channel.unary_unary(
                '/poppie.PoppieService/GetCode',
                request_serializer=poppie_dot_poppie__pb2.GetCodeRequest.SerializeToString,
                response_deserializer=poppie_dot_poppie__pb2.GetCodeResponse.FromString,
                _registered_method=True)
        self.ListSecrets = channel.unary_unary(
                '/poppie.PoppieService/ListSecrets',
                request_serializer=poppie_dot_poppie__pb2.ListSecretsRequest.SerializeToString,
                response_deserializer=poppie_dot_poppie__pb2.ListSecretsResponse.FromString,
                _registered_method=True)
        self.DeleteSecret = channel.unary_unary(
                '/poppie.PoppieService/DeleteSecret',
                request_serializer=poppie_dot_poppie__pb2.DeleteSecretRequest.SerializeToString,
                response_deserializer=poppie_dot_poppie__pb2.DeleteSecretResponse.FromString,
                _registered_method=True)


class PoppieServiceServicer(object):
    """PoppieService provides TOTP secret management and code generation.
    """

    def StoreSecret(self, request, context):
        """StoreSecret stores a new TOTP secret in the vault.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCode(self, request, context):
        """GetCode generates a current TOTP code for a stored secret.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSecrets(self, request, context):
        """ListSecrets returns the labels of all stored secrets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSecret(self, request, context):
        """DeleteSecret removes a secret from the vault.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PoppieServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreSecret,
                    request_deserializer=poppie_dot_poppie__pb2.StoreSecretRequest.FromString,
                    response_serializer=poppie_dot_poppie__pb2.StoreSecretResponse.SerializeToString,
            ),
            'GetCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCode,
                    request_deserializer=poppie_dot_poppie__pb2.GetCodeRequest.FromString,
                    response_serializer=poppie_dot_poppie__pb2.GetCodeResponse.SerializeToString,
            ),
            'ListSecrets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSecrets,
                    request_deserializer=poppie_dot_poppie__pb2.ListSecretsRequest.FromString,
                    response_serializer=poppie_dot_poppie__pb2.ListSecretsResponse.SerializeToString,
            ),
            'DeleteSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSecret,
                    request_deserializer=poppie_dot_poppie__pb2.DeleteSecretRequest.FromString,
                    response_serializer=poppie_dot_poppie__pb2.DeleteSecretResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'poppie.PoppieService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('poppie.PoppieService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PoppieService(object):
    """PoppieService provides TOTP secret management and code generation.
    """

    @staticmethod
    def StoreSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/poppie.PoppieService/StoreSecret',
            poppie_dot_poppie__pb2.StoreSecretRequest.SerializeToString,
            poppie_dot_poppie__pb2.StoreSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/poppie.PoppieService/GetCode',
            poppie_dot_poppie__pb2.GetCodeRequest.SerializeToString,
            poppie_dot_poppie__pb2.GetCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSecrets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/poppie.PoppieService/ListSecrets',
            poppie_dot_poppie__pb2.ListSecretsRequest.SerializeToString,
            poppie_dot_poppie__pb2.ListSecretsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/poppie.PoppieService/DeleteSecret',
            poppie_dot_poppie__pb2.DeleteSecretRequest.SerializeToString,
            poppie_dot_poppie__pb2.DeleteSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
