// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/poppie/poppie.proto

package poppie

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Algorithm specifies the HMAC algorithm used for TOTP generation.
type Algorithm int32

const (
	// ALGORITHM_UNSPECIFIED defaults to SHA1.
	Algorithm_ALGORITHM_UNSPECIFIED Algorithm = 0
	// ALGORITHM_SHA1 is the most common TOTP algorithm (RFC 6238 default).
	Algorithm_ALGORITHM_SHA1 Algorithm = 1
	// ALGORITHM_SHA256 uses SHA-256 for HMAC.
	Algorithm_ALGORITHM_SHA256 Algorithm = 2
	// ALGORITHM_SHA512 uses SHA-512 for HMAC.
	Algorithm_ALGORITHM_SHA512 Algorithm = 3
)

// Enum value maps for Algorithm.
var (
	Algorithm_name = map[int32]string{
		0: "ALGORITHM_UNSPECIFIED",
		1: "ALGORITHM_SHA1",
		2: "ALGORITHM_SHA256",
		3: "ALGORITHM_SHA512",
	}
	Algorithm_value = map[string]int32{
		"ALGORITHM_UNSPECIFIED": 0,
		"ALGORITHM_SHA1":        1,
		"ALGORITHM_SHA256":      2,
		"ALGORITHM_SHA512":      3,
	}
)

func (x Algorithm) Enum() *Algorithm {
	p := new(Algorithm)
	*p = x
	return p
}

func (x Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_poppie_poppie_proto_enumTypes[0].Descriptor()
}

func (Algorithm) Type() protoreflect.EnumType {
	return &file_proto_poppie_poppie_proto_enumTypes[0]
}

func (x Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Algorithm.Descriptor instead.
func (Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_proto_poppie_poppie_proto_rawDescGZIP(), []int{0}
}

// Secret represents a stored TOTP secret.
type Secret struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// label is the human-readable identifier for this secret (e.g. "github.com").
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// secret is the base32-encoded TOTP secret key.
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	// algorithm is the HMAC algorithm to use.
	Algorithm Algorithm `protobuf:"varint,3,opt,name=algorithm,proto3,enum=poppie.Algorithm" json:"algorithm,omitempty"`
	// digits is the number of digits in the generated code (typically 6 or 8).
	Digits uint32 `protobuf:"varint,4,opt,name=digits,proto3" json:"digits,omitempty"`
	// period is the time step in seconds (typically 30).
	Period uint32 `protobuf:"varint,5,opt,name=period,proto3" json:"period,omitempty"`
	// created_at is when the secret was first stored.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// last_used_at is when a code was last generated for this secret.
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_proto_poppie_poppie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poppie_poppie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_proto_poppie_poppie_proto_rawDescGZIP(), []int{0}
}

func (x *Secret) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Secret) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Secret) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (x *Secret) GetDigits() uint32 {
	if x != nil {
		return x.Digits
	}
	return 0
}

func (x *Secret) GetPeriod() uint32 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *Secret) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Secret) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

// StoreSecretRequest contains the details of a TOTP secret to store.
type StoreSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// label is the human-readable identifier (e.g. "github.com").
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// secret is the base32-encoded TOTP secret key.
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	// algorithm is the HMAC algorithm (defaults to SHA1 if unspecified).
	Algorithm Algorithm `protobuf:"varint,3,opt,name=algorithm,proto3,enum=poppie.Algorithm" json:"algorithm,omitempty"`
	// digits is the code length (defaults to 6 if 0).
	Digits uint32 `protobuf:"varint,4,opt,name=digits,proto3" json:"digits,omitempty"`
	// period is the time step in seconds (defaults to 30 if 0).
	Period        uint32 `protobuf:"varint,5,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreSecretRequest) Reset() {
	*x = StoreSecretRequest{}
	mi := &file_proto_poppie_poppie_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreSecretRequest) ProtoMessage() {}

func (x *StoreSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poppie_poppie_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreSecretRequest.ProtoReflect.Descriptor instead.
func (*StoreSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_poppie_poppie_proto_rawDescGZIP(), []int{1}
}

func (x *StoreSecretRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *StoreSecretRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *StoreSecretRequest) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (x *StoreSecretRequest) GetDigits() uint32 {
	if x != nil {
		return x.Digits
	}
	return 0
}

func (x *StoreSecretRequest) GetPeriod() uint32 {
	if x != nil {
		return x.Period
	}
	return 0
}

// StoreSecretResponse confirms storage and includes a verification code.
type StoreSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// label echoes the stored secret's label.
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// verification_code is a current TOTP code to verify the secret works.
	VerificationCode string `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StoreSecretResponse) Reset() {
	*x = StoreSecretResponse{}
	mi := &file_proto_poppie_poppie_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreSecretResponse) ProtoMessage() {}

func (x *StoreSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poppie_poppie_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreSecretResponse.ProtoReflect.Descriptor instead.
func (*StoreSecretResponse) Descriptor() ([]byte, []int) {
	return file_proto_poppie_poppie_proto_rawDescGZIP(), []int{2}
}

func (x *StoreSecretResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *StoreSecretResponse) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

// GetCodeRequest identifies which secret to generate a code for.
type GetCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// label is the identifier of the secret.
	Label         string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCodeRequest) Reset() {
	*x = GetCodeRequest{}
	mi := &file_proto_poppie_poppie_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCodeRequest) ProtoMessage() {}

func (x *GetCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poppie_poppie_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCodeRequest.ProtoReflect.Descriptor instead.
func (*GetCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_poppie_poppie_proto_rawDescGZIP(), []int{3}
}

func (x *GetCodeRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// GetCodeResponse contains the generated TOTP code.
type GetCodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code is the current TOTP code.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// valid_for_seconds is how many seconds until this code expires.
	ValidForSeconds uint32 `protobuf:"varint,2,opt,name=valid_for_seconds,json=validForSeconds,proto3" json:"valid_for_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCodeResponse) Reset() {
	*x = GetCodeResponse{}
	mi := &file_proto_poppie_poppie_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCodeResponse) ProtoMessage() {}

func (x *GetCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poppie_poppie_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCodeResponse.ProtoReflect.Descriptor instead.
func (*GetCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_poppie_poppie_proto_rawDescGZIP(), []int{4}
}

func (x *GetCodeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetCodeResponse) GetValidForSeconds() uint32 {
	if x != nil {
		return x.ValidForSeconds
	}
	return 0
}

// ListSecretsRequest has no parameters.
type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_proto_poppie_poppie_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poppie_poppie_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_proto_poppie_poppie_proto_rawDescGZIP(), []int{5}
}

// ListSecretsResponse contains all stored secret labels.
type ListSecretsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// labels is the list of stored secret identifiers.
	Labels        []string `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_proto_poppie_poppie_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poppie_poppie_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_proto_poppie_poppie_proto_rawDescGZIP(), []int{6}
}

func (x *ListSecretsResponse) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// DeleteSecretRequest identifies the secret to remove.
type DeleteSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// label is the identifier of the secret to delete.
	Label         string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_proto_poppie_poppie_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poppie_poppie_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_poppie_poppie_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSecretRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// DeleteSecretResponse confirms deletion.
type DeleteSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// deleted indicates whether a secret was actually removed.
	Deleted       bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_proto_poppie_poppie_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poppie_poppie_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_proto_poppie_poppie_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSecretResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// VaultContents is the internal format stored encrypted on disk.
type VaultContents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// secrets is the list of all stored TOTP secrets.
	Secrets       []*Secret `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultContents) Reset() {
	*x = VaultContents{}
	mi := &file_proto_poppie_poppie_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultContents) ProtoMessage() {}

func (x *VaultContents) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poppie_poppie_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultContents.ProtoReflect.Descriptor instead.
func (*VaultContents) Descriptor() ([]byte, []int) {
	return file_proto_poppie_poppie_proto_rawDescGZIP(), []int{9}
}

func (x *VaultContents) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

var File_proto_poppie_poppie_proto protoreflect.FileDescriptor

const file_proto_poppie_poppie_proto_rawDesc = "" +
	"\n" +
	"\x19proto/poppie/poppie.proto\x12\x06poppie\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x02\n" +
	"\x06Secret\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12/\n" +
	"\talgorithm\x18\x03 \x01(\x0e2\x11.poppie.AlgorithmR\talgorithm\x12\x16\n" +
	"\x06digits\x18\x04 \x01(\rR\x06digits\x12\x16\n" +
	"\x06period\x18\x05 \x01(\rR\x06period\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\xa3\x01\n" +
	"\x12StoreSecretRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12/\n" +
	"\talgorithm\x18\x03 \x01(\x0e2\x11.poppie.AlgorithmR\talgorithm\x12\x16\n" +
	"\x06digits\x18\x04 \x01(\rR\x06digits\x12\x16\n" +
	"\x06period\x18\x05 \x01(\rR\x06period\"X\n" +
	"\x13StoreSecretResponse\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12+\n" +
	"\x11verification_code\x18\x02 \x01(\tR\x10verificationCode\"&\n" +
	"\x0eGetCodeRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"Q\n" +
	"\x0fGetCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12*\n" +
	"\x11valid_for_seconds\x18\x02 \x01(\rR\x0fvalidForSeconds\"\x14\n" +
	"\x12ListSecretsRequest\"-\n" +
	"\x13ListSecretsResponse\x12\x16\n" +
	"\x06labels\x18\x01 \x03(\tR\x06labels\"+\n" +
	"\x13DeleteSecretRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"0\n" +
	"\x14DeleteSecretResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"9\n" +
	"\rVaultContents\x12(\n" +
	"\asecrets\x18\x01 \x03(\v2\x0e.poppie.SecretR\asecrets*f\n" +
	"\tAlgorithm\x12\x19\n" +
	"\x15ALGORITHM_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eALGORITHM_SHA1\x10\x01\x12\x14\n" +
	"\x10ALGORITHM_SHA256\x10\x02\x12\x14\n" +
	"\x10ALGORITHM_SHA512\x10\x032\xa6\x02\n" +
	"\rPoppieService\x12F\n" +
	"\vStoreSecret\x12\x1a.poppie.StoreSecretRequest\x1a\x1b.poppie.StoreSecretResponse\x12:\n" +
	"\aGetCode\x12\x16.poppie.GetCodeRequest\x1a\x17.poppie.GetCodeResponse\x12F\n" +
	"\vListSecrets\x12\x1a.poppie.ListSecretsRequest\x1a\x1b.poppie.ListSecretsResponse\x12I\n" +
	"\fDeleteSecret\x12\x1b.poppie.DeleteSecretRequest\x1a\x1c.poppie.DeleteSecretResponseB.Z,github.com/BarkingIguana/poppie/proto/poppieb\x06proto3"

var (
	file_proto_poppie_poppie_proto_rawDescOnce sync.Once
	file_proto_poppie_poppie_proto_rawDescData []byte
)

func file_proto_poppie_poppie_proto_rawDescGZIP() []byte {
	file_proto_poppie_poppie_proto_rawDescOnce.Do(func() {
		file_proto_poppie_poppie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_poppie_poppie_proto_rawDesc), len(file_proto_poppie_poppie_proto_rawDesc)))
	})
	return file_proto_poppie_poppie_proto_rawDescData
}

var file_proto_poppie_poppie_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_poppie_poppie_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_poppie_poppie_proto_goTypes = []any{
	(Algorithm)(0),                // 0: poppie.Algorithm
	(*Secret)(nil),                // 1: poppie.Secret
	(*StoreSecretRequest)(nil),    // 2: poppie.StoreSecretRequest
	(*StoreSecretResponse)(nil),   // 3: poppie.StoreSecretResponse
	(*GetCodeRequest)(nil),        // 4: poppie.GetCodeRequest
	(*GetCodeResponse)(nil),       // 5: poppie.GetCodeResponse
	(*ListSecretsRequest)(nil),    // 6: poppie.ListSecretsRequest
	(*ListSecretsResponse)(nil),   // 7: poppie.ListSecretsResponse
	(*DeleteSecretRequest)(nil),   // 8: poppie.DeleteSecretRequest
	(*DeleteSecretResponse)(nil),  // 9: poppie.DeleteSecretResponse
	(*VaultContents)(nil),         // 10: poppie.VaultContents
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_proto_poppie_poppie_proto_depIdxs = []int32{
	0,  // 0: poppie.Secret.algorithm:type_name -> poppie.Algorithm
	11, // 1: poppie.Secret.created_at:type_name -> google.protobuf.Timestamp
	11, // 2: poppie.Secret.last_used_at:type_name -> google.protobuf.Timestamp
	0,  // 3: poppie.StoreSecretRequest.algorithm:type_name -> poppie.Algorithm
	1,  // 4: poppie.VaultContents.secrets:type_name -> poppie.Secret
	2,  // 5: poppie.PoppieService.StoreSecret:input_type -> poppie.StoreSecretRequest
	4,  // 6: poppie.PoppieService.GetCode:input_type -> poppie.GetCodeRequest
	6,  // 7: poppie.PoppieService.ListSecrets:input_type -> poppie.ListSecretsRequest
	8,  // 8: poppie.PoppieService.DeleteSecret:input_type -> poppie.DeleteSecretRequest
	3,  // 9: poppie.PoppieService.StoreSecret:output_type -> poppie.StoreSecretResponse
	5,  // 10: poppie.PoppieService.GetCode:output_type -> poppie.GetCodeResponse
	7,  // 11: poppie.PoppieService.ListSecrets:output_type -> poppie.ListSecretsResponse
	9,  // 12: poppie.PoppieService.DeleteSecret:output_type -> poppie.DeleteSecretResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_poppie_poppie_proto_init() }
func file_proto_poppie_poppie_proto_init() {
	if File_proto_poppie_poppie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_poppie_poppie_proto_rawDesc), len(file_proto_poppie_poppie_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_poppie_poppie_proto_goTypes,
		DependencyIndexes: file_proto_poppie_poppie_proto_depIdxs,
		EnumInfos:         file_proto_poppie_poppie_proto_enumTypes,
		MessageInfos:      file_proto_poppie_poppie_proto_msgTypes,
	}.Build()
	File_proto_poppie_poppie_proto = out.File
	file_proto_poppie_poppie_proto_goTypes = nil
	file_proto_poppie_poppie_proto_depIdxs = nil
}
